//
//  StyleKitCalculator.h
//  ProjectName
//
//  Created by Christian Andersen on 10/10/2016.
//  Copyright (c) 2016 Snake-Apps. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitCalculator : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* multiplypressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* muliplynormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* dividepressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* dividenormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* addPressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* addnormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* minusnormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* minusPressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* onepressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* onenormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* twonormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* twopressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* threepressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* threenormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* fournormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* fourpressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* fivenormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* fivepressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* sixpressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* sixnormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* sevenpressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* sevennormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* eightpressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* eightnormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* ninepressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* ninenormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* zeronormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* zeropressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* commanormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* commaPressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* equalpressedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* equalnormalTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* shakeMeTargets;

// Drawing Methods
+ (void)drawMultiplypressed;
+ (void)drawMuliplynormal;
+ (void)drawDividepressed;
+ (void)drawDividenormal;
+ (void)drawAddPressed;
+ (void)drawAddnormal;
+ (void)drawMinusnormal;
+ (void)drawMinusPressed;
+ (void)drawOnepressed;
+ (void)drawOnenormal;
+ (void)drawTwonormal;
+ (void)drawTwopressed;
+ (void)drawThreepressed;
+ (void)drawThreenormal;
+ (void)drawFournormal;
+ (void)drawFourpressed;
+ (void)drawFivenormal;
+ (void)drawFivepressed;
+ (void)drawSixpressed;
+ (void)drawSixnormal;
+ (void)drawSevenpressed;
+ (void)drawSevennormal;
+ (void)drawEightpressed;
+ (void)drawEightnormal;
+ (void)drawNinepressed;
+ (void)drawNinenormal;
+ (void)drawZeronormal;
+ (void)drawZeropressed;
+ (void)drawCommanormal;
+ (void)drawCommaPressed;
+ (void)drawEqualpressed;
+ (void)drawEqualnormal;
+ (void)drawShakeMe;

// Generated Images
+ (UIImage*)imageOfMultiplypressed;
+ (UIImage*)imageOfMuliplynormal;
+ (UIImage*)imageOfDividepressed;
+ (UIImage*)imageOfDividenormal;
+ (UIImage*)imageOfAddPressed;
+ (UIImage*)imageOfAddnormal;
+ (UIImage*)imageOfMinusnormal;
+ (UIImage*)imageOfMinusPressed;
+ (UIImage*)imageOfOnepressed;
+ (UIImage*)imageOfOnenormal;
+ (UIImage*)imageOfTwonormal;
+ (UIImage*)imageOfTwopressed;
+ (UIImage*)imageOfThreepressed;
+ (UIImage*)imageOfThreenormal;
+ (UIImage*)imageOfFournormal;
+ (UIImage*)imageOfFourpressed;
+ (UIImage*)imageOfFivenormal;
+ (UIImage*)imageOfFivepressed;
+ (UIImage*)imageOfSixpressed;
+ (UIImage*)imageOfSixnormal;
+ (UIImage*)imageOfSevenpressed;
+ (UIImage*)imageOfSevennormal;
+ (UIImage*)imageOfEightpressed;
+ (UIImage*)imageOfEightnormal;
+ (UIImage*)imageOfNinepressed;
+ (UIImage*)imageOfNinenormal;
+ (UIImage*)imageOfZeronormal;
+ (UIImage*)imageOfZeropressed;
+ (UIImage*)imageOfCommanormal;
+ (UIImage*)imageOfCommaPressed;
+ (UIImage*)imageOfEqualpressed;
+ (UIImage*)imageOfEqualnormal;
+ (UIImage*)imageOfShakeMe;

@end
